default_language_version:
  python: python3.11

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py39-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: update-changelog
        name: Update Changelog
        entry: bash
        language: system
        args: ["-c", "poetry run git-changelog -B auto", ">!", "./CHANGELOG.md"]
        pass_filenames: false
        files: ''
        types: [file]

  # Run the Ruff formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff-format

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
