from loguru import logger

from horiba_sdk.communication import Command, Response
from horiba_sdk.devices.device_manager import DeviceManager

from .abstract_device import AbstractDevice


class Monochromator(AbstractDevice):
    """_summary_
    This class is a refactored version of the MonoApiTest class. It has the same functionality,
    but is more object oriented. It also inherits from the AbstractDevice class, which is a generic
    device class. It follows SOLID principles, and is more easily extensible.
    Its behavior is described here:
    1. On initialization, it creates an instance of the DeviceManager class, which is a singleton.
    2. From this device manager, it gets a reference to the CommunicationManager and stores it internally to send
    and receive commands.
    3. It calls its own private _home function to home the monochromator.

    Args:
        AbstractDevice (_type_): _description_
    """

    def __init__(self, device_id: int, device_manager: DeviceManager) -> None:
        """_summary_
        This function initializes the monochromator. It calls the super class's init function, and then calls its own
        _open and _home functions.
        """
        super().__init__(device_manager, device_id)
        self._open()
        logger.info('Monochromator initialized.')
        self._home()

    def _open(self) -> None:
        """_summary_
        This function opens the connection to the monochromator. It creates a command object with the command json that
        looks like:
        {"id": 1, //autogenerated by the command class
        "command": "mono_open",
        "parameters": {
        "id": 0, //monochromator id, zero-indexed, self._mono_id used
        }
        """
        command = Command('mono_open', {'id': self._device_id})
        self._communicator.send_and_receive(command)

    def _home(self) -> None:
        """_summary_
        This function homes the monochromator.
        It creates a command object with the command string and parameters, and sends it to the communication manager.
        """
        command = Command('mono_init', {'id': self._device_id})
        self._communicator.send_and_receive(command)

    @property
    def is_mono_busy(self) -> bool:
        """_summary_
        This function checks if the monochromator is busy.
        It creates a command object with the command string and parameters, and sends it to the communication manager.
        It then receives the response and returns a boolean value.
        """
        command = Command('is_mono_busy', {'id': self._device_id})
        self._communicator.send(command)
        response: Response = self._communicator.response()
        if type(response) is Response:
            return response.parameters['busy']
        else:
            return False

    def _close(self) -> None:
        raise NotImplementedError
